Move remaining CircleCI jobs to GitHub Actions
ci.yml's "component-lint" job runs `make lint` in all four components,
and varies by Debian version (except proxy/bookworm).

test.yml's "component" job runs `make test` in all components except
client. The "client" job runs the test-functional, test-integration, and
test-random targets and installs the extra dependencies needed (now in
client/Makefile).

test.yml also has "internationalization", which checks strings have been
extracted and are reproducible.

Some parts of GitHub's UI makes it inconvenient to have a ton of jobs in
one file, so tests have been split out into their own for solely that
reason.

Dependencies that aren't needed were dropped as part of this (e.g.
libnotify-bin, libmagic1, python3-dev, etc.). Same with the `export
PYTHONPATH=$PYTHONPATH:.` pattern (the current directory is always on
the Python path...).

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,6 +52,52 @@ jobs:
       - name: Run lint
         run: make lint
 
+  # Run `make lint` across all components
+  component-lint:
+    strategy:
+      fail-fast: false
+      matrix:
+        component:
+          - client
+          - export
+          - log
+          - proxy
+        debian_version:
+          - bullseye
+          - bookworm
+        # bookworm jobs are failing and will be
+        # replaced with proxy v2 shortly, so skip
+        # https://github.com/freedomofpress/securedrop-client/issues/1681
+        exclude:
+          - component: proxy
+            debian_version: bookworm
+    runs-on: ubuntu-latest
+    container: debian:${{ matrix.debian_version }}
+    steps:
+      - run: |
+          apt-get update && apt-get install --yes git make gnupg
+      - uses: actions/checkout@v4
+      - name: Install dependencies
+        run: |
+          source /etc/os-release
+          if [[ "$VERSION_CODENAME" == "bullseye" ]]; then
+              # Install Poetry via PyPI
+              apt-get install --yes --no-install-recommends python3-pip
+              pip install poetry==1.6.1
+          elif [[ "$VERSION_CODENAME" == "bookworm" ]]; then
+              # Install Poetry via system package
+              apt-get install --yes --no-install-recommends python3-poetry
+          else
+              echo "Unsupported Debian version: $VERSION_CODENAME"
+              exit 1
+          fi
+          poetry -C ${{ matrix.component }} install
+          if [[ "${{ matrix.component }}" == "client" ]]; then
+            make -C ${{ matrix.component }} ci-install-deps
+          fi
+      - name: Run lint
+        run: make -C ${{ matrix.component }} lint
+
   safety:
     runs-on: ubuntu-latest
     container: debian:bookworm
